#!/bin/sh +e
# Run init scripts and CMD

TMP_EXEC_FILE="/tmp/_init.d_exec_file"

echo "=== Running init scripts ==="
# All files with an extension will be executed.
for FILE in $CONTAINER_DIR/init.d/*.*; do
	if [ -f "$FILE" ]; then
		echo "------ [ $FILE ]"

		# Directory may or should be read only because it's mounted from host.
		cp "$FILE" "$TMP_EXEC_FILE"
		chmod +x "$TMP_EXEC_FILE"
		
		# Execute a temporary copy instead
		"$TMP_EXEC_FILE"
		CODE="$?"
		
		if [ "$CODE" -ne "0" ]; then
			echo "##### Init script \"$FILE\" failed with exit code: $CODE #####" >&2
			exit 1
		fi
		
		# Clean up file
		rm -rf "$TMP_EXEC_FILE"
	fi
done
echo "=== Done with all init scripts ==="

# Run CMD
echo "=== Starting CMD ==="
exec "$@"
